<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>json</string>
	</array>
	<key>name</key>
	<string>Azure Resource Manager</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#value</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<!-- Constant (json.org) -->
		<key>constant</key>
		<dict>
			<key>match</key>
			<string>\b(?:true|false|null)\b</string>
			<key>name</key>
			<string>constant.language.source.azure-resource-manager</string>
		</dict>

		<!-- Number (json.org) -->
		<key>number</key>
		<dict>
			<key>match</key>
			<string>(?x:-?(?:0|[1-9]\d*)(?:(?:\.\d+)?(?:[eE][+-]?\d+)?)?)</string>
			<key>name</key>
			<string>constant.numeric.source.azure-resource-manager</string>
		</dict>

		<!-- Double quoted string (json.org) -->
		<key>double-quoted-string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.azure-resource-manager</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(")|(\n)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.azure-resource-manager</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.unclosed-string.azure-resource-manager</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.double.azure-resource-manager</string>
					<key>patterns</key>
					<array>
						<!-- Escape characters (json.org) -->
						<dict>
							<key>match</key>
							<string>(?x:\\(?:["\\/bfnrt]|u[0-9a-fA-F]{4}))</string>
							<key>name</key>
							<string>constant.character.escape.azure-resource-manager</string>
						</dict>
						<!-- Invalid \uxxxx escape sequences -->
						<dict>
							<key>match</key>
							<string>\\u[^"]{,4}</string>
							<key>name</key>
							<string>invalid.illegal.unrecognized-string-escape.azure-resource-manager</string>
						</dict>
						<!-- Unrecognized escaped litterals -->
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>invalid.illegal.unrecognized-string-escape.azure-resource-manager</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>

		<!-- Single quoted string - Not available at json.org - It is used in ARM expressions -->
		<key>single-quoted-string</key>
		<dict>
			<key>patterns</key>
			<array>
				<!-- Single quoted - not at json.org, yet accepted by some parsers -->
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.azure-resource-manager</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(')|(\n)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.azure-resource-manager</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.unclosed-string.azure-resource-manager</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.quoted.single.azure-resource-manager</string>
					<key>patterns</key>
					<array>
						<!-- Escape characters (json.org) -->
						<dict>
							<key>match</key>
							<string>(?x:\\(?:['\\/bfnrt]|u[0-9a-fA-F]{4}))</string>
							<key>name</key>
							<string>constant.character.escape.azure-resource-manager</string>
						</dict>
						<!-- Invalid \uxxxx escape sequences -->
						<dict>
							<key>match</key>
							<string>\\u[^']{,4}</string>
							<key>name</key>
							<string>invalid.illegal.unrecognized-string-escape.azure-resource-manager</string>
						</dict>
						<!-- Unrecognized escaped litterals -->
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>invalid.illegal.unrecognized-string-escape.azure-resource-manager</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>

		<!-- Double or single quoted string -->
		<key>string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#double-quoted-string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#single-quoted-string</string>
				</dict>
			</array>
		</dict>

		<!-- Generic Javascript style comments - not at json.org, yet accepted by ARM -->
		<key>comment-generic</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.azure-resource-manager</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.azure-resource-manager</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.azure-resource-manager</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(//).*$\n?</string>
					<key>name</key>
					<string>comment.line.double-slash.azure-resource-manager</string>
				</dict>
			</array>
		</dict>

		<!-- Special comments: NOTE:, TODO: ... -->
		<key>comment-note</key>
		<dict>
			<key>match</key>
			<string>(//)\s*((?:BUG|FIXME|TODO|HACK|NOTE):?).*$\n?</string>
			<key>name</key>
			<string>comment.line.note.azure-resource-manager</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.azure-resource-manager</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.line.note.azure-resource-manager</string>
				</dict>
			</dict>
		</dict>

		<!-- All comments as accepted by ARM -->
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment-note</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment-generic</string>
				</dict>
			</array>
		</dict>

		<!-- ARM expression (https://msdn.microsoft.com/en-us/library/azure/dn835138.aspx#bk_expressions) -->
		<key>arm-expression</key>
		<dict>
			<key>begin</key>
			<string>(")(\[)(?=[^\[])(?=[^"\]]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.azure-resource-manager</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.item-access.arguments.azure-resource-manager</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\])(")</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>meta.item-access.arguments.azure-resource-manager</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.azure-resource-manager</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.azure-resource-manager</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#arm-expression-body</string>
				</dict>
			</array>
		</dict>

		<!-- ARM Methods - Take no parameter and return an object (https://azure.microsoft.com/en-us/documentation/articles/resource-group-template-functions/#variables) -->
		<key>arm-method-invocation-expression</key>
		<dict>
			<key>match</key>
			<string>(resourceGroup|subscription|deployment|copyindex)(\()(\s*|[^)]+)(\))</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.azure-resource-manager</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.azure-resource-manager</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>invalid.illegal.parameter.azure-resource-manager</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.azure-resource-manager</string>
				</dict>
			</dict>
			<key>name</key>
			<string>support.function.azure-resource-manager</string>
		</dict>

		<!-- ARM paramters / variables (https://azure.microsoft.com/en-us/documentation/articles/resource-group-template-functions/#variables) -->
		<key>arm-parameter-or-variable-reference</key>
		<dict>
			<key>begin</key>
			<string>(variables|parameters)(\()(?=\s*'[^']+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.azure-resource-manager</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.azure-resource-manager</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.azure-resource-manager</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single.azure-resource-manager</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#single-quoted-string</string>
				</dict>
			</array>
		</dict>

		<!-- ARM dotted path (.property1.anArray[index].property2 ...) -->
		<key>arm-expression-dotted-path</key>
		<dict>
			<key>match</key>
			<string>(\.)([^\.\[\]]+)(?:(\[)(?:([0-9]+)|([^\]]*))(\]))?</string>
			<key>name</key>
			<string></string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.dereference.azure-resource-manager</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>meta.property-name.azure-resource-manager</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.dereference.azure-resource-manager</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.source.azure-resource-manager</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>invalid.source.azure-resource-manager</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.dereference.azure-resource-manager</string>
				</dict>
			</dict>
		</dict>

		<!-- ARM expression body - everything in "[ ... ]" -->
		<key>arm-expression-body</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#arm-method-invocation-expression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#arm-parameter-or-variable-reference</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#arm-expression-dotted-path</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#arm-unary-string-manipulation-function</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#single-quoted-string</string>
				</dict>
			</array>
		</dict>

		<!-- ARM unary string manipulation like concat(), base64() ... -->
		<key>arm-unary-string-manipulation-function</key>
		<dict>
			<key>begin</key>
			<string>(concat|base64|toLower|toUpper)(\()(?=.+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.azure-resource-manager</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.azure-resource-manager</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\)</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.parameters.azure-resource-manager</string>
				</dict>
			</dict>
			<key>name</key>
			<string></string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#arm-expression-body</string>
				</dict>
			</array>
		</dict>


		<!-- ARM well known object properties (location, tags ...) double quoted -->
		<key>arm-well-known-property-double-quoted</key>
		<dict>
			<key>match</key>
			<string>(")(contentVersion|parameters|variables|resources|outputs|location|apiVersion|name|type|tags|dependsOn|properties|plan|defaultValue|allowedValues|metadata|copy|count)(")</string>
			<key>name</key>
			<string>support.variable.azure-resource-manager</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.azure-resource-manager</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.azure-resource-manager</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.azure-resource-manager</string>
				</dict>
			</dict>
		</dict>

		<!-- ARM well known object properties (location, tags ...) single quoted -->
		<key>arm-well-known-property-single-quoted</key>
		<dict>
			<key>match</key>
			<string>(')(contentVersion|parameters|variables|resources|outputs|location|apiVersion|name|type|tags|dependsOn|properties|plan|defaultValue|allowedValues|metadata|copy|count)(')</string>
			<key>name</key>
			<string>support.variable.azure-resource-manager</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.azure-resource-manager</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.azure-resource-manager</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.azure-resource-manager</string>
				</dict>
			</dict>
		</dict>

		<!-- A Json object property name definition - Either a regular object property definition or an ARM intrinsic property -->
		<key>json-property-definition</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#arm-well-known-property-double-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#arm-well-known-property-single-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
			</array>
		</dict>

		<!-- Array (json.org) -->
		<key>array</key>
		<dict>
			<key>begin</key>
			<string>\[</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.array.begin.azure-resource-manager</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\]</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.array.end.azure-resource-manager</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.structure.array.azure-resource-manager</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#value</string>
				</dict>
				<dict>
					<key>match</key>
					<string>,</string>
					<key>name</key>
					<string>punctuation.separator.array.azure-resource-manager</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[^\s\]]</string>
					<key>name</key>
					<string>invalid.illegal.expected-array-separator.azure-resource-manager</string>
				</dict>
			</array>
		</dict>

		<!-- Object (json.org) -->
		<key>object</key>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.dictionary.begin.azure-resource-manager</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.dictionary.end.azure-resource-manager</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.structure.dictionary.azure-resource-manager</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#json-property-definition</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>:</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.dictionary.key-value.azure-resource-manager</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(,)|(?=\})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.dictionary.pair.azure-resource-manager</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.structure.dictionary.value.azure-resource-manager</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>comment</key>
							<string>the JSON object value</string>
							<key>include</key>
							<string>#value</string>
						</dict>
						<dict>
							<key>match</key>
							<string>[^\s,]</string>
							<key>name</key>
							<string>invalid.illegal.expected-dictionary-separator.azure-resource-manager</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>[^\s\}]</string>
					<key>name</key>
					<string>invalid.illegal.expected-dictionary-separator.azure-resource-manager</string>
				</dict>
			</array>
		</dict>

		<!-- Json value (json.org) with Azure Resource manager specific syntax -->
		<key>value</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#number</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#arm-expression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#array</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#object</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.azure-resource-manager</string>
	<key>uuid</key>
	<string>F6EB7FA5-3FC6-4265-85B7-6E6EF52FF335</string>
</dict>
</plist>